#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : googleapis-common-protos
Version  : 1.53.0
Release  : 14
URL      : https://files.pythonhosted.org/packages/1f/4a/369a8b1cf12089c1a902101b0431729e02cd2dd4e390377c920aa1d3ccab/googleapis-common-protos-1.53.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/1f/4a/369a8b1cf12089c1a902101b0431729e02cd2dd4e390377c920aa1d3ccab/googleapis-common-protos-1.53.0.tar.gz
Summary  : Common protobufs used in Google APIs
Group    : Development/Tools
License  : Apache-2.0
Requires: googleapis-common-protos-license = %{version}-%{release}
Requires: googleapis-common-protos-python = %{version}-%{release}
Requires: googleapis-common-protos-python3 = %{version}-%{release}
Requires: grpcio
Requires: protobuf
BuildRequires : buildreq-distutils3
BuildRequires : grpcio
BuildRequires : protobuf

%description
# Google APIs common protos

%package license
Summary: license components for the googleapis-common-protos package.
Group: Default

%description license
license components for the googleapis-common-protos package.


%package python
Summary: python components for the googleapis-common-protos package.
Group: Default
Requires: googleapis-common-protos-python3 = %{version}-%{release}

%description python
python components for the googleapis-common-protos package.


%package python3
Summary: python3 components for the googleapis-common-protos package.
Group: Default
Requires: python3-core
Provides: pypi(googleapis_common_protos)
Requires: pypi(protobuf)

%description python3
python3 components for the googleapis-common-protos package.


%prep
%setup -q -n googleapis-common-protos-1.53.0
cd %{_builddir}/googleapis-common-protos-1.53.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1627686093
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/googleapis-common-protos
cp %{_builddir}/googleapis-common-protos-1.53.0/LICENSE %{buildroot}/usr/share/package-licenses/googleapis-common-protos/2b8b815229aa8a61e483fb4ba0588b8b6c491890
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/googleapis-common-protos/2b8b815229aa8a61e483fb4ba0588b8b6c491890

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
